### ISSUE TITLE
Synthesized circuits have 2-qubit gates with > 3 CNOTs

### ISSUE THREAD

**Issue by aaronszasz** [BQSKit/bqskit#118]
In some cases, synthesizing eg a 3-qubit unitary gives a block with 4 or 5 layers of e.g. 
`cx q[1], q[2];`
separated by single-qubit gates.

This seems like an easy type of block to look for, then the number of CNOTs on the same pair of qubits can be limited to no more than 3 in a row.

**Comment by edyounis** [comment]
Yep! Thanks for bringing this to our attention. Awesome suggestion! We will get this fixed shortly.
