### ISSUE TITLE
For `append_circuit`, default location when appended circuit is the size of the whole circuit

### ISSUE THREAD

**Issue by aaronszasz** [BQSKit/bqskit#120]
Minor request: when using `Circuit.append_circuit`, it would be convenient if the `location` parameter were optional in the case that the appended circuit and the circuit it's appended to are the same size.

**Comment by edyounis** [comment]
Currently, this can be done with `circuit + other` or `circuit += other`. In partitioning, the `append_circuit` is used extensively when adding a subcircuit on a subset of qubits, so I think it is good to still have `location` required in this method. Nevertheless, thank you for the suggestion! Keep them coming :)
