### ISSUE TITLE
`DaggerGate` vs actually inverting the gate, qasm output for `DaggerGate`

### ISSUE THREAD

**Issue by aaronszasz** [BQSKit/bqskit#121]
The `get_inverse` method currently returns `DaggerGate` objects.  For small gates (single-qubit gates, CNOT, etc), is there a reason to save these as, eg, `DaggerGate(CNOTGate)` rather than just computing the adjoint (in this case, again CNOT)?

The rough use case is something like 
U^dg @ O @ U @ psi,
where U is given by some circuit.  

One might then want to print the full circuit, including reversed gates, to qasm (currently not possible with `DaggerGate`).  Also to get gate counts where `DaggerGate(CNOTGate)` is just counted as `CNOTGate`

**Comment by edyounis** [comment]
Awesome suggestion! We can accomplish this by adding a get_inverse method to the gates themselves with a default being the current DaggerGate setup.

**Comment by WolfLink** [comment]
You should be able to invert most of the parameterized gates simply by negating the parameters (and then re-normalizing to the 0-2pi range if desired).

**Comment by Aaron-Robertson** [comment]
I'm giving this one a shot, looks interesting!
