### ISSUE TITLE
bqskitrs installation errors

### ISSUE THREAD

**Issue by mtweiden** [BQSKit/bqskit#137]
When trying to `pip install -e .` bqskit, I get the error `ERROR: No matching distribution found for bqskitrs>=0.3.0`. Changing `setup.cfg` so that it says `bqskitrs>=0.3.0rc1` fixes the issue, but I'm not sure if this is the preferred way to do things?

**Comment by alonkukl** [comment]
On which branch are you?

**Comment by mtweiden** [comment]
This is on a local branch of `master`.

**Comment by edyounis** [comment]
There is a similar error on the bqskitrs branch: https://github.com/BQSKit/bqskitrs/issues/10

This might be fixed with 1.1-dev. Can you try on that branch?

**Comment by mtweiden** [comment]
I had to change it for 1.1-dev as well.
