### ISSUE TITLE
Broken import of qasm 

### ISSUE THREAD

**Issue by rakytap** [BQSKit/bqskit#159]
Dear Developers,

I tried out your bqskit package. When installing the version 1.0.4 of the package from pip  I could import a circuit from a qasm file.
However, when I cloned the package from the GitHub repository (either branch master or tag 1.0.4), the following code snippet gives an error:

    from bqskit.ir import Circuit

    circuit = Circuit.from_file('heisenberg-16-20.qasm')

    for gate in circuit.gate_set:
        print(f"{gate} Count:", circuit.count(gate))

The error message indicates that qasm files are not supported in the package:

Traceback (most recent call last):
  File "/home/laci/kutatas/test2.py", line 3, in <module>
    circuit = Circuit.from_file('heisenberg-16-20.qasm')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laci/kutatas/bqskit/bqskit/ir/circuit.py", line 3164, in from_file
    language = get_language(filename.split('.')[-1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laci/kutatas/bqskit/bqskit/ir/lang/__init__.py", line 17, in get_language
    raise ValueErro

Could you help us to resolve  this issue?

Best regards, Peter

**Comment by edyounis** [comment]
Hi Peter, thanks for the bug report.

It seems like the error message is cut off a bit, was there any additional message there?

In any case, can you try the 1.1-dev branch to see if the issue is resolved? We will be pushing an update soon, so hopefully this is already fixed.

**Comment by rakytap** [comment]
It seems to work, even in the master branch.  I don't see a reason why it was not working before... Thanks for your help.
