### ISSUE TITLE
`ShiftGate` documentation page equation broken

### ISSUE THREAD

**Issue by natestemen** [BQSKit/bqskit#185]
## Problem
<img width="534" alt="Screenshot 2023-09-17 at 10 50 03 AM" src="https://github.com/BQSKit/bqskit/assets/12703123/4c83c9d5-83f4-4587-b2b5-3d05c12d8c45">

## Code
Looks to be coming from these lines: https://github.com/BQSKit/bqskit/blob/7ce7713e1dccfbafdfbcc01f4fe07c5b2f79c73c/bqskit/ir/gates/constant/shift.py#L31-L34

**Comment by edyounis** [comment]
Thanks for reporting this!

**Comment by edyounis** [comment]
Seems there is also an issue with the clockgate, csumgate, hgate, pdgate, and fsimgate.
