### ISSUE TITLE
Compiler Call raising an issue

### ISSUE THREAD

**Issue by mwalidcharrwi** [BQSKit/bqskit#213]
Hi,

I have been calling the compiler call after passing a workflow to it and the error is as follows:

Exception ignored in: <function Compiler.__del__ at 0x7f966cdc8430>
Traceback (most recent call last):
  File "./conda/envs/quantum-venv/lib/python3.10/site-packages/bqskit/compiler/compiler.py", line 227, in __del__
TypeError: 'NoneType' object is not callable

**Comment by alonkukl** [comment]
Hi, 

Can you please share the workflow you are trying to run?, or maybe even a minimal reproducible code?

Alon

**Comment by edyounis** [comment]
@alonkukl Thanks for responding so quickly! This issue arose during a meeting, and I know the details. I will be looking into this shortly.

**Comment by edyounis** [comment]
@mwalidcharrwi Are you importing or using `atexit` directly in your code at all?

**Comment by mwalidcharrwi** [comment]
@edyounis @alonkukl thanks for your response no there is no `atexit` imported in the code. Only bqskit.passes and bqskit.compiler (compiler and compilation task) is imported.
I will do that and share it with you.

**Comment by mwalidcharrwi** [comment]
@edyounis I sent you an invitation for the private repository with the script uploaded

**Comment by edyounis** [comment]
From the [python docs](https://docs.python.org/3/reference/datamodel.html): 

> [\_\_del\_\_()](https://docs.python.org/3/reference/datamodel.html#object.__del__) can be executed during interpreter shutdown. As a consequence, the global variables it needs to access (including other modules) may already have been deleted or set to None. Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the [__del__()](https://docs.python.org/3/reference/datamodel.html#object.\_\_del\_\_) method is called.

It seems like the atexit module is being deleted before the compiler is being finalized causing the `atexit.register` to become None. This is definitely a bug, and we should reconsider the use of `__del__` in the Compiler class.

After looking at your code, @mwalidcharrwi, I see that you do not call `compiler.close()` or use the `Compiler` in a context manager. To avoid this issue currently, you should ensure to cleanup the compiler resource either with the `close` method, or by using it in a `with` block.

**Comment by mwalidcharrwi** [comment]
I will consider adding that to the code I shared. Thanks for the recommendation @edyounis  

However, I've added the `compiler.close()` to the BQSKIT workflow that we had setup previously and the same issue is encountered but occasionally compared to the code shared. 

Just to give you a guide for the algorithm:

```
compiler = compiler()

workflow = BQSKIT workflow 

compiler.close()
```

**Comment by edyounis** [comment]
@mwalidcharrwi Can you check if the commit 1004c05 fixed this issue? I am unable to reproduce locally. You may want to checkout the runtime-upgrades branch in #237 PR to test. This branch is very much active development, so I don't recommend using it other than testing if the issue is fixed.
