### ISSUE TITLE
Is it possible to get the QASM string representation of a BQSKit circuit?

### ISSUE THREAD

**Issue by jagandecapri** [BQSKit/bqskit#214]
Hi,

Is it possible to get the QASM string representation of a BQSKit circuit?

**Comment by mtweiden** [comment]
Hi Jagatheesan,

You can save circuits using `Circuit.save('file_name.qasm')`. Here's an example:

```
from bqskit import Circuit
from bqskit.ir.gates import CNOTGate

circuit = Circuit(2)
circuit.append_gate(CNOTGate(), (0, 1))

circuit.save('circuit.qasm')
```

**Comment by jagandecapri** [comment]
Hi @mtweiden ,

Thank you for your response and sorry if my question was not clear. I am looking for a way to get the QASM **string** from a BQSKit circuit saved into a variable like [here](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#qasm).

**Comment by edyounis** [comment]
Yes, the `circuit.to` method will return the qasm as a `str` the way you have called it.

Thanks for reporting this bug. We should always be able to save a qasm file that we read. This happens because the `cu1` gets internally converted to a `ControlledGate(U1Gate)` and the `ControlledGate` doesn't support qasm encoding, unlike the specialized controlled gates, e.g. `CXGate()`.

**Comment by jagandecapri** [comment]
Hi @edyounis , noted. I tried to see if I can do a workaround by converting the BQSKit to Qiskit and then use the `circuit.qasm()` method from Qiskit but I end up with the same error `AttributeError: 'ControlledGate' object has no attribute '_qasm_name'` when executing `qc = bqskit_to_qiskit(circuit)` as following:

```python
from bqskit import Circuit
from bqskit.ext import bqskit_to_qiskit
circuit = Circuit.from_file('qasm/test_circuit.qasm')
qc = bqskit_to_qiskit(circuit)
qc.qasm()
```

If you know any workaround for this issue, please kindly let me know. It seems to me that I cannot have "non-specialised" controlled gates in the BQSKit circuit and convert the resulting circuit to QASM.

**Comment by edyounis** [comment]
There is really no low-effort workaround here, but @mtweiden put up a PR that we will get merged in shortly.
