### ISSUE TITLE
Support Topology-Aware Synthesis

### ISSUE THREAD

**Issue by WolfLink** [BQSKit/bqskit#22]
In order to support topology-aware synthesis via search, the layer generator needs to be able to take a topology as input.  This could be done in the [SimpleLayerGenerator](https://github.com/BQSKit/bqskit/blob/master/bqskit/compiler/search/generators/simple.py).

**Comment by edyounis** [comment]
Topology information should either be generated at the beginning of pass execution or by a LayoutPass (soon-to-come). This information can be passed directly to all the other passes via the `data` dict. The LayerGenerator, I believe, also has access to this dict. The passes should assume all-to-all connectivity if no topology information is found in the `data` dict.
