### ISSUE TITLE
New Release after Qiskit v1 Update

### ISSUE THREAD

**Issue by nquetschlich** [BQSKit/bqskit#238]
Hi there, I was wondering whether you are planning a new release soon? 

The reason I am asking is that we are currently updating MQT Predictor to support Qiskit v1.0 and since BQSKit is a dependency, we would need #228 to be released.

**Comment by edyounis** [comment]
It's hard to put a date on the next major release, however, I will explore a 1.1.2 patch with this fix this week.

**Comment by edyounis** [comment]
Patch release 1.1.2 is up. Closing for now, but feel free to re-open if there are continuing issues.
