### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by nquetschlich** [BQSKit/bqskit#251]
Hi there, I was wondering whether you plan to do a new release soon because I would love to include the newly added `ECRGate` (which was merged in https://github.com/BQSKit/bqskit/pull/234) in our MQT Predictor framework.

**Comment by edyounis** [comment]
The next release is a few months away; however, I will happily release a patch for a bug blocking you. I am sorry for the inconvenience. You should still be able to copy the code from the ECRGate into your repo as a temporary fix. BQSKit's compilation routines can handle user-defined gates all the same.
