### ISSUE TITLE
Would it be better to have DAG and bqskit circuit conversion?

### ISSUE THREAD

**Issue by jinleic** [BQSKit/bqskit#252]
As in the title, would it be better to have functions like dag_to_circuit() and circuit_to_dag() ?

There is some painful inconsistency problem when trying to extract a sub-circuit and put back an equivalent sub-circuit.

**Comment by edyounis** [comment]
> There is some painful inconsistency problem when trying to extract a sub-circuit and put back an equivalent sub-circuit.

Can you elaborate?

**Comment by edyounis** [comment]
We do have DAG methods as part of the circuit: `next()`, `prev()`, `front()`, `rear()`. Additionally, we have `fold()` and `replace()` or `replace_with_circuit()` to help with replacing subcircuits. Closing for now, feel free to re-open if you think any of these methods can be improved or more should be added.
